module.exports = {
    node: {
      NODE_ENV: "DEVELOPMENT",
    },
    token: {
      TOKEN_EXPIRE_TIME: 86400,
    },
    messages: {
      INVALID_DATA: "INVALID_DATA",
      BAD_REQUEST: "BAD_REQUEST",
      INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
      INVALID_FILE_NAME: "INVALID_FILE_NAME",
      AUTHORIZATION_REQUIRED: "AUTHORIZATION_REQUIRED",
      USER_ALREADY_EXIST: "USER_ALREADY_EXIST",
      CREATE_SUCCESSFUL: "CREATE_SUCCESSFUL",
      INVALID_EMAIL_OR_PASSWORD: "INVALID_EMAIL_OR_PASSWORD",
      UNAUTHORIZED: "UNAUTHORIZED",
      INVALID_IMAGE_FORMAT: "INVALID_IMAGE_FORMAT",
      BAD_REQUEST_NUMBER: 400,
      NOT_FOUND: 404,
      UNAUTHORIZED: 401,
      SUCCESSFUL: 200,
      CREATE_SUCCESSFUL: 201,
      INTERNAL_SERVER_ERROR: 500,
    },
  };